### ISSUE TITLE
Kurse

### ISSUE THREAD

**Issue by Witcher01** [LearningBay24/LearningBay24-backend#23]
* [x] erstellen
* [x] lesen
  * [x] Kurs abrufen
  * [x] Kursteilnehmer anzeigen
* [x] editieren
  * [x] Kursteilnehmer entfernen
* [x] löschen

**Comment by Witcher01** [comment]
@Schorzel Bitte Issue überprüfen. Was ist fertig, etc.

Wenn nichts mehr offen ist bitte schließen

**Comment by Schorzel** [comment]
Added in commit 5ba07277a31b143217bc666a20fb4f7804418f22
