### ISSUE TITLE
Einbindung der Abgabenfristen und Prüfungen im Kalender?

### ISSUE THREAD

**Issue by SirasEagle** [LearningBay24/LearningBay24-backend#35]
Im Gegensatz zu Course haben Exam und Submission keinen Appointments, Darstellung auf dem Kalender?
Vermutlich durch Exam.Date und Submission.Date, die beim Laden des Kalenders raus gezogen werden.

Kalender benötigt also von der Exam vermutlich noch die weiteren Informationen zur Darstellung..?

**Comment by Witcher01** [comment]
> Kalender benötigt also von der Exam vermutlich noch die weiteren Informationen zur Darstellung..?

Was ist damit gemeint?

**Comment by Witcher01** [comment]
Achso, klar 👍🏼
