### ISSUE TITLE
add API for calendar

### ISSUE THREAD

**Issue by SirasEagle** [LearningBay24/LearningBay24-backend#44]
API für Kalender muss hinzugefügt und implementiert werden.
Appointments werden hinzugefügt, Submissions mit dem submission.date und Exams mit dem exam.date

**Comment by Witcher01** [comment]
@Dominik2497 @pruf1 Ist die API für den Kalender schon festgelegt?

**Comment by Witcher01** [comment]
@SirasEagle wie weit ist das?

**Comment by SirasEagle** [comment]
Die API? Also Holen aller Appointments, holen der Appointments für einen gegebenen Zeitraum, Hinzufügen eines Appointments und glaub das Holen aller Abgaben ist drin
@Witcher01

**Comment by Witcher01** [comment]
Wann testest du das? Bzw. bis wann bist du dann mit den Appointments insgesamt fertig?

**Comment by Witcher01** [comment]
Alles klar, danke fürs Update.
