### ISSUE TITLE
Zurückgegebene Informationen über einen User limitieren

### ISSUE THREAD

**Issue by Witcher01** [LearningBay24/LearningBay24-backend#47]
Bspw. muss das Passwort niemals zurückgegeben werden.
Andere Felder sollten auch berücksichtigt werden.

Was wird zurückgegeben, wenn ein anderer User angefragt wird?

**Comment by Witcher01** [comment]
@Icola1 was brauchst du alles an Informationen?

**Comment by Icola1** [comment]
title, firstname, surname, e-mail, role_id, graduation_level, Semester, phone_number, residence, (profile_picture ist wahrscheinlich wegen der größe als eigene funktion sinnvoll oder?), biography, preffered_language

Damit kann man eine sinnvolle Profilseite anzeigen.
Soll zum prüfen von Berechtigungen wo z.b. nur eine role_id benötigt wird eine eigene Funktion erstellt werden oder arbeite ich mit dem kompletten user?

**Comment by Witcher01** [comment]
> profile_picture ist wahrscheinlich wegen der größe als eigene funktion sinnvoll oder?

denke auch, ja.

> Soll zum prüfen von Berechtigungen wo z.b. nur eine role_id benötigt wird eine eigene Funktion erstellt werden oder arbeite ich mit dem kompletten user?

TBH ich weiß nicht ganz was du meinst. Wenn du nur die `role_id` brauchst, dann arbeite nur mit der.

**Comment by Icola1** [comment]
es gibt keinen endpunkt der nur die roleId zurückgibt soll der erstellt werden oder bleiben wir bei get user weil da die roleid mitdabei ist
